# Generated by Django 5.1 on 2024-09-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebServerApp', '0002_temperaturereading_humidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
